project_id = "imobflux"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://127.0.0.1:3000/convite", "http://localhost:3000/convite"]

[auth.email]
otp_expiry = 3600

[auth.email.template.invite]
subject = "Convite para a equipe ImobFlux"
content_path = "./supabase/templates/invite.html"

[db.seed]
enabled = false
